COURSE_CATALOG = [
    # ─── SOFTWARE ENGINEERING (12 courses) ───
    {"course_id": "SE-PY1", "title": "Python Fundamentals", "domain": "software_engineering", "skill_tags": ["Python", "programming basics", "data structures"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Core Python syntax, loops, functions, and OOP."},
    {"course_id": "SE-PY2", "title": "Advanced Python Engineering", "domain": "software_engineering", "skill_tags": ["Python", "design patterns", "performance optimization"], "level": "advanced", "duration_hours": 12, "prerequisites": ["SE-PY1"], "description": "Decorators, metaclasses, concurrency, and production-grade Python."},
    {"course_id": "SE-JS1", "title": "JavaScript Deep Dive", "domain": "software_engineering", "skill_tags": ["JavaScript", "ES6+", "async programming"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Modern JavaScript: closures, promises, modules, and event loop."},
    {"course_id": "SE-TS1", "title": "TypeScript Essentials", "domain": "software_engineering", "skill_tags": ["TypeScript", "type systems", "JavaScript"], "level": "beginner", "duration_hours": 10, "prerequisites": [], "description": "TypeScript fundamentals: types, interfaces, generics, and framework integration."},
    {"course_id": "SE-RC1", "title": "React from Scratch", "domain": "software_engineering", "skill_tags": ["React", "component architecture", "hooks", "state management"], "level": "beginner", "duration_hours": 14, "prerequisites": ["SE-JS1"], "description": "Build SPAs with React: components, hooks, routing, and state."},
    {"course_id": "SE-RC2", "title": "Advanced React Patterns", "domain": "software_engineering", "skill_tags": ["React", "performance optimization", "advanced patterns", "state management"], "level": "advanced", "duration_hours": 10, "prerequisites": ["SE-RC1"], "description": "Render optimization, compound components, suspense, and concurrent features."},
    {"course_id": "SE-ND1", "title": "Node.js Backend Development", "domain": "software_engineering", "skill_tags": ["Node.js", "Express", "REST APIs", "server-side JavaScript"], "level": "intermediate", "duration_hours": 14, "prerequisites": ["SE-JS1"], "description": "Scalable server-side apps with Node.js, Express, and async patterns."},
    {"course_id": "SE-API1", "title": "RESTful API Design", "domain": "software_engineering", "skill_tags": ["REST API Design", "API versioning", "authentication"], "level": "intermediate", "duration_hours": 8, "prerequisites": [], "description": "Design robust REST APIs: versioning, auth, pagination, and error handling."},
    {"course_id": "SE-SD1", "title": "System Design Fundamentals", "domain": "software_engineering", "skill_tags": ["System Design", "scalability", "distributed systems", "architecture"], "level": "intermediate", "duration_hours": 12, "prerequisites": [], "description": "Design large-scale systems: load balancing, caching, sharding, microservices."},
    {"course_id": "SE-GT1", "title": "Git & Collaborative Development", "domain": "software_engineering", "skill_tags": ["Git", "version control", "code review"], "level": "beginner", "duration_hours": 6, "prerequisites": [], "description": "Git workflows, branching strategies, PR reviews, and conflict resolution."},
    {"course_id": "SE-TDD1", "title": "Testing & TDD Masterclass", "domain": "software_engineering", "skill_tags": ["Unit Testing", "Integration Testing", "Test-Driven Development"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Unit tests, integration tests, mocking, coverage, and TDD workflow."},
    {"course_id": "SE-CL1", "title": "AWS Cloud Practitioner Path", "domain": "software_engineering", "skill_tags": ["AWS", "cloud computing", "EC2", "S3", "Lambda"], "level": "beginner", "duration_hours": 12, "prerequisites": [], "description": "Core AWS services: compute, storage, networking, and serverless."},

    # ─── DATA SCIENCE (11 courses) ───
    {"course_id": "DS-SQL1", "title": "SQL Mastery", "domain": "data_science", "skill_tags": ["SQL", "database design", "query optimization"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "SQL from SELECT to window functions, joins, and subqueries."},
    {"course_id": "DS-PG1", "title": "PostgreSQL Deep Dive", "domain": "data_science", "skill_tags": ["PostgreSQL", "database design", "SQL optimization", "indexing"], "level": "intermediate", "duration_hours": 10, "prerequisites": ["DS-SQL1"], "description": "Advanced PostgreSQL: indexing, query plans, and production management."},
    {"course_id": "DS-PD1", "title": "Data Analysis with Pandas", "domain": "data_science", "skill_tags": ["Pandas", "Data Analysis", "NumPy", "data wrangling"], "level": "beginner", "duration_hours": 10, "prerequisites": ["SE-PY1"], "description": "Data manipulation, cleaning, and analysis with Pandas and NumPy."},
    {"course_id": "DS-VIZ1", "title": "Data Visualization Bootcamp", "domain": "data_science", "skill_tags": ["Data Visualization", "Matplotlib", "storytelling with data"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Create compelling charts: Matplotlib, Seaborn, and dashboard design."},
    {"course_id": "DS-ML1", "title": "Machine Learning Foundations", "domain": "data_science", "skill_tags": ["Machine Learning", "Scikit-learn", "supervised learning", "model evaluation"], "level": "intermediate", "duration_hours": 16, "prerequisites": ["DS-PD1"], "description": "Regression, classification, clustering, and model evaluation with Scikit-learn."},
    {"course_id": "DS-DL1", "title": "Deep Learning with PyTorch", "domain": "data_science", "skill_tags": ["Deep Learning", "PyTorch", "neural networks", "Computer Vision"], "level": "advanced", "duration_hours": 18, "prerequisites": ["DS-ML1"], "description": "CNNs, RNNs, transformers, and training loops with PyTorch."},
    {"course_id": "DS-NLP1", "title": "Natural Language Processing", "domain": "data_science", "skill_tags": ["Natural Language Processing", "text classification", "transformers"], "level": "advanced", "duration_hours": 14, "prerequisites": ["DS-ML1"], "description": "Text preprocessing, embeddings, sentiment analysis, and LLMs."},
    {"course_id": "DS-STAT1", "title": "Statistics for Data Science", "domain": "data_science", "skill_tags": ["Statistical Modeling", "Hypothesis Testing", "A/B Testing"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Probability, distributions, hypothesis tests, and experimental design."},
    {"course_id": "DS-FE1", "title": "Feature Engineering Workshop", "domain": "data_science", "skill_tags": ["Feature Engineering", "data preprocessing", "model performance"], "level": "intermediate", "duration_hours": 8, "prerequisites": ["DS-ML1"], "description": "Create predictive features: encoding, scaling, selection, and pipelines."},
    {"course_id": "DS-ETL1", "title": "ETL & Data Pipelines", "domain": "data_science", "skill_tags": ["ETL Pipelines", "Apache Spark", "data engineering"], "level": "intermediate", "duration_hours": 12, "prerequisites": ["DS-SQL1"], "description": "Build ETL pipelines with Airflow, Spark, and modern data stack."},
    {"course_id": "DS-MDB1", "title": "MongoDB Essentials", "domain": "data_science", "skill_tags": ["MongoDB", "NoSQL", "document databases"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Document modeling, CRUD, aggregation, and indexing in MongoDB."},

    # ─── PRODUCT MANAGEMENT (10 courses) ───
    {"course_id": "PM-AG1", "title": "Agile & Scrum Certification Prep", "domain": "product_management", "skill_tags": ["Agile Methodologies", "Scrum", "sprint planning"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Scrum framework, ceremonies, roles, and agile principles."},
    {"course_id": "PM-PS1", "title": "Product Strategy Masterclass", "domain": "product_management", "skill_tags": ["Product Strategy", "Product Roadmapping", "vision setting"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Define product vision, strategy, and build compelling roadmaps."},
    {"course_id": "PM-AN1", "title": "Product Analytics & Metrics", "domain": "product_management", "skill_tags": ["Product Analytics", "KPI Definition", "data-driven decisions"], "level": "intermediate", "duration_hours": 8, "prerequisites": [], "description": "Define KPIs, build dashboards, and make data-driven product decisions."},
    {"course_id": "PM-US1", "title": "User Story & Requirements Workshop", "domain": "product_management", "skill_tags": ["User Story Writing", "Requirements Gathering", "acceptance criteria"], "level": "beginner", "duration_hours": 6, "prerequisites": [], "description": "Write effective user stories, acceptance criteria, and requirements docs."},
    {"course_id": "PM-SM1", "title": "Stakeholder Management", "domain": "product_management", "skill_tags": ["Stakeholder Management", "communication", "executive alignment"], "level": "intermediate", "duration_hours": 6, "prerequisites": [], "description": "Manage stakeholders, align executives, and navigate organizational politics."},
    {"course_id": "PM-MR1", "title": "Market Research Methods", "domain": "product_management", "skill_tags": ["Market Research", "Competitive Analysis", "Customer Discovery"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Competitive analysis, market sizing, TAM/SAM/SOM, and research frameworks."},
    {"course_id": "PM-GTM1", "title": "Go-to-Market Playbook", "domain": "product_management", "skill_tags": ["Go-to-Market Strategy", "launch planning", "positioning"], "level": "intermediate", "duration_hours": 8, "prerequisites": ["PM-PS1"], "description": "Plan and execute product launches: positioning, channels, and metrics."},
    {"course_id": "PM-OKR1", "title": "OKR Implementation Guide", "domain": "product_management", "skill_tags": ["OKR Framework", "goal setting", "team alignment"], "level": "beginner", "duration_hours": 4, "prerequisites": [], "description": "Set and track OKRs: objectives, key results, and cascading goals."},
    {"course_id": "PM-PR1", "title": "Prioritization Frameworks", "domain": "product_management", "skill_tags": ["Feature Prioritization", "RICE scoring", "decision making"], "level": "intermediate", "duration_hours": 6, "prerequisites": [], "description": "RICE, ICE, MoSCoW, and weighted scoring for feature prioritization."},
    {"course_id": "PM-PMF1", "title": "Finding Product-Market Fit", "domain": "product_management", "skill_tags": ["Product-Market Fit", "User Interviews", "validation"], "level": "advanced", "duration_hours": 10, "prerequisites": ["PM-MR1"], "description": "Validate ideas, run experiments, and measure product-market fit signals."},

    # ─── DESIGN & UX (10 courses) ───
    {"course_id": "DX-UI1", "title": "UI Design Principles", "domain": "design_ux", "skill_tags": ["User Interface Design", "Visual Design", "Typography", "Color Theory"], "level": "beginner", "duration_hours": 10, "prerequisites": [], "description": "Visual hierarchy, typography, color, and layout fundamentals."},
    {"course_id": "DX-UX1", "title": "UX Research & Design", "domain": "design_ux", "skill_tags": ["User Experience Design", "User Research", "Persona Development"], "level": "beginner", "duration_hours": 12, "prerequisites": [], "description": "User research methods, personas, journey maps, and UX strategy."},
    {"course_id": "DX-FG1", "title": "Figma Professional Workflow", "domain": "design_ux", "skill_tags": ["Figma", "Prototyping", "Design Systems"], "level": "intermediate", "duration_hours": 10, "prerequisites": ["DX-UI1"], "description": "Advanced Figma: auto-layout, components, variants, and team libraries."},
    {"course_id": "DX-WF1", "title": "Wireframing & Prototyping", "domain": "design_ux", "skill_tags": ["Wireframing", "Prototyping", "Interaction Design"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Lo-fi to hi-fi wireframes, interactive prototypes, and design iteration."},
    {"course_id": "DX-DS1", "title": "Design Systems at Scale", "domain": "design_ux", "skill_tags": ["Design Systems", "component libraries", "tokens"], "level": "advanced", "duration_hours": 12, "prerequisites": ["DX-FG1"], "description": "Build and maintain design systems: tokens, components, and governance."},
    {"course_id": "DX-A11Y1", "title": "Accessibility (WCAG) Compliance", "domain": "design_ux", "skill_tags": ["Accessibility (WCAG)", "inclusive design", "screen readers"], "level": "intermediate", "duration_hours": 8, "prerequisites": [], "description": "WCAG 2.1 guidelines, ARIA, keyboard navigation, and audit tools."},
    {"course_id": "DX-IA1", "title": "Information Architecture", "domain": "design_ux", "skill_tags": ["Information Architecture", "navigation design", "content strategy"], "level": "intermediate", "duration_hours": 8, "prerequisites": [], "description": "Structure content: sitemaps, card sorting, tree testing, and taxonomy."},
    {"course_id": "DX-UT1", "title": "Usability Testing Lab", "domain": "design_ux", "skill_tags": ["Usability Testing", "user feedback", "test facilitation"], "level": "intermediate", "duration_hours": 6, "prerequisites": ["DX-UX1"], "description": "Plan, facilitate, and analyze usability tests: moderated and unmoderated."},
    {"course_id": "DX-MD1", "title": "Motion Design for UI", "domain": "design_ux", "skill_tags": ["Motion Design", "micro-interactions", "animation principles"], "level": "intermediate", "duration_hours": 8, "prerequisites": ["DX-UI1"], "description": "Purposeful animation: easing, timing, transitions, and micro-interactions."},
    {"course_id": "DX-RD1", "title": "Responsive & Adaptive Design", "domain": "design_ux", "skill_tags": ["Responsive Design", "CSS", "mobile-first design"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Design for every screen: breakpoints, fluid grids, and mobile-first CSS."},

    # ─── OPERATIONS & LOGISTICS (10 courses) ───
    {"course_id": "OPS-DK1", "title": "Docker & Containerization", "domain": "operations_logistics", "skill_tags": ["Docker", "containers", "Docker Compose", "image building"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Containerize applications: images, volumes, networks, and multi-container."},
    {"course_id": "OPS-K8S1", "title": "Kubernetes in Production", "domain": "operations_logistics", "skill_tags": ["Kubernetes", "container orchestration", "deployments", "scaling"], "level": "advanced", "duration_hours": 16, "prerequisites": ["OPS-DK1"], "description": "Deploy and manage Kubernetes clusters: pods, services, and Helm charts."},
    {"course_id": "OPS-CI1", "title": "CI/CD Pipeline Engineering", "domain": "operations_logistics", "skill_tags": ["CI/CD Pipelines", "GitHub Actions", "automated testing", "deployment"], "level": "intermediate", "duration_hours": 10, "prerequisites": ["OPS-DK1"], "description": "Design CI/CD pipelines: GitHub Actions, testing, and blue-green deployments."},
    {"course_id": "OPS-TF1", "title": "Infrastructure as Code with Terraform", "domain": "operations_logistics", "skill_tags": ["Infrastructure as Code", "Terraform", "provisioning"], "level": "intermediate", "duration_hours": 12, "prerequisites": [], "description": "Manage infrastructure: Terraform providers, modules, and state management."},
    {"course_id": "OPS-LX1", "title": "Linux Administration Essentials", "domain": "operations_logistics", "skill_tags": ["Linux Administration", "shell scripting", "system management"], "level": "beginner", "duration_hours": 10, "prerequisites": [], "description": "Linux fundamentals: file systems, processes, networking, and shell scripting."},
    {"course_id": "OPS-MON1", "title": "Monitoring & Observability", "domain": "operations_logistics", "skill_tags": ["Monitoring & Observability", "Prometheus", "Grafana", "alerting"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Set up monitoring: Prometheus, Grafana, dashboards, and alerting rules."},
    {"course_id": "OPS-SEC1", "title": "Network Security Fundamentals", "domain": "operations_logistics", "skill_tags": ["Network Security", "firewalls", "encryption", "threat modeling"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Secure networks: firewalls, TLS, IAM, and vulnerability assessment."},
    {"course_id": "OPS-SCM1", "title": "Supply Chain Management", "domain": "operations_logistics", "skill_tags": ["Supply Chain Management", "logistics", "procurement"], "level": "beginner", "duration_hours": 10, "prerequisites": [], "description": "End-to-end supply chain: procurement, logistics, and inventory optimization."},
    {"course_id": "OPS-LEAN1", "title": "Lean Operations & Six Sigma", "domain": "operations_logistics", "skill_tags": ["Lean Management", "Six Sigma", "Process Optimization"], "level": "intermediate", "duration_hours": 12, "prerequisites": [], "description": "Lean tools, DMAIC, value stream mapping, and waste elimination."},
    {"course_id": "OPS-IM1", "title": "Incident Management & SRE", "domain": "operations_logistics", "skill_tags": ["Incident Management", "SRE practices", "on-call management"], "level": "intermediate", "duration_hours": 8, "prerequisites": [], "description": "Incident response, post-mortems, SLOs, and reliability engineering."},

    # ─── FINANCE & ACCOUNTING (9 courses) ───
    {"course_id": "FN-FA1", "title": "Financial Analysis Fundamentals", "domain": "finance_accounting", "skill_tags": ["Financial Analysis", "Financial Reporting", "ratio analysis"], "level": "beginner", "duration_hours": 10, "prerequisites": [], "description": "Read financial statements, compute ratios, and assess company health."},
    {"course_id": "FN-FM1", "title": "Financial Modeling in Excel", "domain": "finance_accounting", "skill_tags": ["Financial Modeling", "Excel Advanced (Financial)", "forecasting"], "level": "intermediate", "duration_hours": 14, "prerequisites": ["FN-FA1"], "description": "Build DCF, LBO, and merger models in Excel with best practices."},
    {"course_id": "FN-BF1", "title": "Budgeting & Forecasting", "domain": "finance_accounting", "skill_tags": ["Budgeting & Forecasting", "planning", "variance analysis"], "level": "beginner", "duration_hours": 8, "prerequisites": [], "description": "Create budgets, rolling forecasts, and variance analysis frameworks."},
    {"course_id": "FN-CF1", "title": "Corporate Finance Essentials", "domain": "finance_accounting", "skill_tags": ["Corporate Finance", "capital structure", "valuation"], "level": "intermediate", "duration_hours": 12, "prerequisites": ["FN-FA1"], "description": "Capital budgeting, WACC, valuation methods, and capital structure."},
    {"course_id": "FN-RM1", "title": "Risk Management Frameworks", "domain": "finance_accounting", "skill_tags": ["Risk Management", "risk assessment", "hedging strategies"], "level": "intermediate", "duration_hours": 10, "prerequisites": [], "description": "Identify, assess, and mitigate financial and operational risks."},
    {"course_id": "FN-ACC1", "title": "Accounting Principles (GAAP)", "domain": "finance_accounting", "skill_tags": ["Accounting Principles (GAAP)", "bookkeeping", "journal entries"], "level": "beginner", "duration_hours": 10, "prerequisites": [], "description": "GAAP fundamentals: double-entry, accrual accounting, and financial statements."},
    {"course_id": "FN-TAX1", "title": "Tax Planning & Strategy", "domain": "finance_accounting", "skill_tags": ["Tax Planning", "tax compliance", "deductions"], "level": "intermediate", "duration_hours": 8, "prerequisites": ["FN-ACC1"], "description": "Tax structures, deductions, credits, and strategic tax planning."},
    {"course_id": "FN-IA1", "title": "Investment Analysis", "domain": "finance_accounting", "skill_tags": ["Investment Analysis", "Portfolio Management", "asset allocation"], "level": "intermediate", "duration_hours": 12, "prerequisites": ["FN-FA1"], "description": "Equity analysis, portfolio theory, asset allocation, and performance attribution."},
    {"course_id": "FN-MA1", "title": "Mergers & Acquisitions", "domain": "finance_accounting", "skill_tags": ["Mergers & Acquisitions", "deal structuring", "due diligence"], "level": "advanced", "duration_hours": 14, "prerequisites": ["FN-FM1"], "description": "M&A process: target screening, due diligence, valuation, and integration."},
]

def get_catalog_dict() -> dict:
    """Return catalog indexed by course_id."""
    return {c["course_id"]: c for c in COURSE_CATALOG}

def get_catalog_size() -> int:
    return len(COURSE_CATALOG)
